# Claude Code Agent Configuration for K-GAY Travel Guides
# This file configures specialized agents for the travel guides project

project: "K-GAY Travel Guides"
description: "LGBTQ+ cruise and travel guide application"
tech_stack:
  - React
  - TypeScript
  - Supabase
  - PostgreSQL
  - Tailwind CSS
  - Vite

# Priority agents for this project
priority_agents:
  ui_ux:
    - name: "ui-ux-designer"
      path: "~/.claude/agents/agents/ui-ux-designer.md"
      use_for:
        - "Mobile responsiveness improvements"
        - "User flow optimization"
        - "Accessibility enhancements"
        - "Visual hierarchy refinement"

    - name: "ui-visual-validator"
      path: "~/.claude/agents/agents/ui-visual-validator.md"
      use_for:
        - "Cross-browser testing"
        - "Visual regression testing"
        - "Component consistency checks"

    - name: "frontend-developer"
      path: "~/.claude/agents/agents/frontend-developer.md"
      use_for:
        - "React component development"
        - "TypeScript improvements"
        - "State management"
        - "Performance optimization"

    - name: "mobile-developer"
      path: "~/.claude/agents/agents/mobile-developer.md"
      use_for:
        - "Mobile-first design implementation"
        - "Touch interactions"
        - "Responsive layouts"
        - "PWA features"

  backend_data:
    - name: "database-optimizer"
      path: "~/.claude/agents/agents/database-optimizer.md"
      use_for:
        - "Supabase query optimization"
        - "Index optimization"
        - "Data model improvements"
        - "Query performance tuning"

    - name: "backend-architect"
      path: "~/.claude/agents/agents/backend-architect.md"
      use_for:
        - "API design"
        - "Service architecture"
        - "Scalability planning"

    - name: "api-documenter"
      path: "~/.claude/agents/agents/api-documenter.md"
      use_for:
        - "API documentation"
        - "Endpoint descriptions"
        - "Usage examples"

  security_testing:
    - name: "security-auditor"
      path: "~/.claude/agents/agents/security-auditor.md"
      use_for:
        - "Authentication security"
        - "Data privacy checks"
        - "SQL injection prevention"
        - "XSS protection"
        - "Supabase RLS policies"

    - name: "test-automator"
      path: "~/.claude/agents/agents/test-automator.md"
      use_for:
        - "E2E test creation"
        - "Component testing"
        - "Integration tests"
        - "Test coverage improvement"

    - name: "performance-engineer"
      path: "~/.claude/agents/agents/performance-engineer.md"
      use_for:
        - "Load time optimization"
        - "Bundle size reduction"
        - "Image optimization"
        - "Caching strategies"

  specialized:
    - name: "typescript-pro"
      path: "~/.claude/agents/agents/typescript-pro.md"
      use_for:
        - "Type safety improvements"
        - "Interface definitions"
        - "Generic implementations"

    - name: "seo-content-writer"
      path: "~/.claude/agents/agents/seo-content-writer.md"
      use_for:
        - "Travel guide content"
        - "Port descriptions"
        - "Meta descriptions"
        - "SEO optimization"

# Project-specific contexts
contexts:
  database:
    type: "Supabase PostgreSQL"
    connection: "Environment variable DATABASE_URL"
    note: "Never use SQLite or Neon commands"

  authentication:
    provider: "Supabase Auth"
    context: "SupabaseAuthContext"
    admin_user: "admin@atlantis.com"

  storage:
    images: "Supabase Storage"
    cdn: "Supabase CDN with transformations"
    categories:
      - "talent-images (22 artists)"
      - "port-images (7 destinations)"
      - "party-theme-images"

  ui_guidelines:
    theme: "Ocean-themed gradients"
    preserve:
      - "Headers and navigation"
      - "Tab bars and ordering"
      - "Banner sections"
      - "Color scheme"
    mobile_breakpoints:
      - "375px (mobile)"
      - "768px (tablet)"
      - "1024px (desktop)"

# Quick commands for common tasks
quick_commands:
  optimize_mobile: |
    Use agents: mobile-developer, ui-ux-designer
    Focus: Mobile responsiveness for cruise guide pages

  security_audit: |
    Use agents: security-auditor, database-optimizer
    Focus: Supabase RLS policies and auth security

  improve_performance: |
    Use agents: performance-engineer, frontend-developer
    Focus: Bundle size, image loading, caching

  test_suite: |
    Use agents: test-automator, ui-visual-validator
    Focus: E2E tests for booking flow and admin panel

  content_seo: |
    Use agents: seo-content-writer, api-documenter
    Focus: Port descriptions and travel guide content

# Agent invocation patterns
invocation_patterns:
  - pattern: "improve mobile experience"
    agents: ["mobile-developer", "ui-ux-designer"]

  - pattern: "optimize database"
    agents: ["database-optimizer", "backend-architect"]

  - pattern: "security review"
    agents: ["security-auditor", "test-automator"]

  - pattern: "performance optimization"
    agents: ["performance-engineer", "frontend-developer"]

  - pattern: "content creation"
    agents: ["seo-content-writer", "ui-ux-designer"]

# Testing requirements
testing:
  required_before_commit:
    - "npm run test:run"
    - "npm run test:e2e"
    - "npm run check"

  coverage_minimums:
    new_features: 80
    bug_fixes: 100
    ui_changes: "visual regression required"

# Development workflow
workflow:
  branch_naming: "feature/[ticket-id]-description"
  commit_style: "conventional commits"
  pr_requirements:
    - "All tests passing"
    - "TypeScript checks clean"
    - "Mobile responsive verified"
    - "Security considerations documented"