[build]
  publish = "dist/public"
  command = "npm install && npm run build:netlify"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production]
  command = "npm install && npm run build:netlify"

[context.deploy-preview]
  command = "npm install && npm run build:netlify"

[context.branch-deploy]
  command = "npm install && npm run build:netlify"

[build.environment]
  NODE_VERSION = "20.10.0"
  SECRETS_SCAN_ENABLED = "false"

[dev]
  functions = "netlify/functions"
  port = 8888
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"