[build]
  publish = "dist/public"
  command = "npm install && npm run build:netlify"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200