[build]
  publish = "dist/public"
  functions = "netlify/functions"
  command = "npm install && npm run build:frontend-only"

[context.production]
  command = "npm install && npm run build:frontend-only"

[context.deploy-preview]
  command = "npm install && npm run build:frontend-only"

[context.branch-deploy]
  command = "npm install && npm run build:frontend-only"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/api/trips/*/complete"
  to = "/.netlify/functions/trips-complete"
  status = 200

[[redirects]]
  from = "/api/trips"
  to = "/.netlify/functions/trips"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"